apiVersion: v1
kind: Secret
metadata:
  name: cloudmart-mysql-secret
  namespace: cloudmart
stringData:
  root-password: cloudmart_root
  password: change_me
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudmart-mysql-pvc
  namespace: cloudmart
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cloudmart
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: cloudmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: {secretKeyRef: {name: cloudmart-mysql-secret, key: root-password}}
            - name: MYSQL_DATABASE
              value: cloudmart
            - name: MYSQL_USER
              value: cloudmart_user
            - name: MYSQL_PASSWORD
              valueFrom: {secretKeyRef: {name: cloudmart-mysql-secret, key: password}}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: cloudmart-mysql-pvc
